import re

file_path = r'c:\Users\Dell1234\.gemini\antigravity\scratch\ml_project\paper_revised_draft.md'

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# 1. Abstract
target_abs = """## Abstract
The efficacy of Text-to-SQL systems in Retrieval-Augmented Generation (RAG) architectures depends heavily on the geometric structure of high-dimensional query embedding spaces. This paper investigates the structural properties of these spaces, comparing the academic Spider benchmark (384D) with a production-scale environment (768D) from a Data Analyst agent from vanna.ai. The pipeline is developed and optimized on the academic baseline benchmark before being scaled and migrated to the production database environment. Using Principal Component Analysis (PCA), the intrinsic dimensionality of the embedding manifold is characterized to identify regions of signal redundancy. This geometric assessment informs the development of a Query Routing Layer employing Support Vector Machines (SVM). By mapping cluster cohesion and identifying geometric dispersion among complex query types, this study demonstrates a principled approach to dimensionality reduction and automated query classification. The findings provide a technical framework for optimizing retrieval latency and infrastructure costs by strategically directing queries to Large Language Models based on their latent geometric characteristics, thereby improving the operational efficiency of enterprise Text-to-SQL pipelines."""

replace_abs = """## Abstract
The efficacy of Text-to-SQL systems in Retrieval-Augmented Generation (RAG) architectures depends heavily on the geometric structure of high-dimensional query embedding spaces. This paper investigates the structural properties of these spaces, comparing the academic Spider benchmark (384D) with a production-scale environment (768D) from a Data Analyst agent. The pipeline is developed and optimized on the academic baseline benchmark before being scaled and migrated to the production database environment. Using Principal Component Analysis (PCA), the intrinsic dimensionality of the embedding manifold is characterized to identify regions of signal redundancy. This geometric assessment informs the development of a Query Routing Layer employing Support Vector Machines (SVM) equipped with a non-linear Radial Basis Function (RBF) kernel. By mapping cluster cohesion and identifying geometric dispersion among complex query types, this study demonstrates a principled approach to dimensionality reduction and automated query classification. The optimized SVM-RBF model achieves high classification accuracy across all complexity levels, enabled by customized class-balancing weights. When scaled to the higher-dimensional production manifold, the classifier benefited from superior geometric separability, yielding a 10-point increase in macro F1-score (from 0.71 to 0.81). The findings provide a technical framework for optimizing retrieval latency and infrastructure costs by strategically directing queries to Large Language Models based on their latent geometric characteristics, resulting in a 70.7% database storage reduction and significant inference cost savings, thereby improving the operational efficiency of enterprise Text-to-SQL pipelines."""

# 2. Introduction
target_intro = """## 1 Introduction
Retrieval-Augmented Generation (RAG) [15] has emerged as a cornerstone architecture for building Text-to-SQL systems, translating natural language questions into executable database queries. By retrieving semantically similar historical question-SQL pairs from a vector database, large language models (LLMs) can leverage in-context learning to generate highly accurate SQL statements. In production environments, such as Sumvec's Data Analyst platform, this architecture enables non-technical enterprise users to query complex databases using natural language. Under the hood, the platform encodes user questions into 384-dimensional dense vectors using the BAAI/bge-small-en-v1.5 embedding model [2]. These embeddings are indexed in a Pinecone vector database [8], enabling real-time cosine similarity search to retrieve relevant query-SQL examples. The retrieved examples are subsequently injected into the prompt of a Claude LLM [12], which generates the final SQL query.

Despite the operational success of this retrieval pipeline, the underlying geometric properties of the embedding space remain uncharacterized. It is unclear whether query embeddings form coherent, separable neighborhoods based on logical and syntactic complexity, or how much of the high-dimensional representation constitutes redundant semantic noise. Standard query retrieval assumes that semantic proximity correlates directly with logical SQL structure. However, if the query embeddings are geometrically dispersed with respect to difficulty, simple vector search may retrieve inappropriate in-context examples, leading to schema mismatches or syntax errors during LLM inference. Furthermore, deploying large, general-purpose LLMs for simple projections is computationally and financially inefficient. Distinguishing simple queries from complex ones directly from their vector representations would enable a query routing layer that directs simpler queries to lower-cost models and reserves premium compute for highly nested queries.

This research addresses this gap by investigating the structure of query embedding spaces across both academic benchmarks (384D) and production environments (768D). To establish a robust routing layer, the initial pipeline optimization, hyperparameter tuning, and kernel selection evaluations were conducted on the baseline Spider dataset [1]. Once optimized, the entire pipeline was scaled and migrated to the 768-dimensional production enterprise database environment. Specifically, the problem is formalized by addressing four core questions:
1. **Intrinsic Dimensionality**: How much of the variance in query embeddings is captured by a small number of principal components, and is the effective dimensionality of the space significantly lower than its nominal dimension? [6]
2. **Geometric Clustering**: Do queries of similar syntactic or semantic complexity cluster together cohesively in the embedding space, or are they geometrically dispersed?
3. **Complexity Classification**: Can a supervised classifier, trained on a low-dimensional projection of the embedding space, reliably distinguish discrete query complexity tiers?
4. **Sensitivity and Trade-offs**: What is the sensitivity of classification performance to the number of PCA components retained, and at what point does further dimensionality reduction degrade downstream classification?

By answering these questions, this study establishes a principled mathematical basis for optimizing vector indices, reducing storage footprints, and constructing high-efficiency query routing layers in enterprise Text-to-SQL systems."""

replace_intro = """## 1 Introduction
Retrieval-Augmented Generation (RAG) [15] has emerged as a cornerstone architecture for building Text-to-SQL systems, translating natural language questions into executable database queries. By retrieving semantically similar historical question-SQL pairs from a vector database, large language models (LLMs) can leverage in-context learning to generate highly accurate SQL statements. In production environments, such as Sumvec's Data Analyst platform, this architecture enables non-technical enterprise users to query complex databases using natural language. Under the hood, the platform encodes user questions into 384-dimensional dense vectors using the BAAI/bge-small-en-v1.5 embedding model [2]. These embeddings are indexed in a Pinecone vector database [8], enabling real-time cosine similarity search to retrieve relevant query-SQL examples. The retrieved examples are subsequently injected into the prompt of a Claude LLM [12], which generates the final SQL query.

Despite the operational success of this retrieval pipeline, the underlying geometric properties of the embedding space remain uncharacterized. It is unclear whether query embeddings form coherent, separable neighborhoods based on logical and syntactic complexity, or how much of the high-dimensional representation constitutes redundant semantic noise. Standard query retrieval assumes that semantic proximity correlates directly with logical SQL structure. However, if the query embeddings are geometrically dispersed with respect to difficulty, simple vector search may retrieve inappropriate in-context examples, leading to schema mismatches or syntax errors during LLM inference. Furthermore, deploying large, general-purpose LLMs for simple projections is computationally and financially inefficient. Distinguishing simple queries from complex ones directly from their vector representations would enable a query routing layer that directs simpler queries to lower-cost models and reserves premium compute for highly nested queries.

From an engineering perspective, the deployment of state-of-the-art LLMs for all queries represents a major operational bottleneck. While simple queries (e.g., retrieving a single column with a basic filter) can be resolved by small, high-throughput models costing a fraction of premium APIs, complex queries (e.g., those involving multiple joins, nested subqueries, and aggregation functions) require the advanced reasoning capabilities of premium models to prevent syntax and schema errors. If a routing layer can classify query difficulty directly from raw embeddings in sub-millisecond time, simple queries can be routed to cheap models and complex queries to premium models, maximizing cost savings. However, building such a routing layer is challenging because SQL difficulty is a logical property, whereas embeddings primarily encode semantic and syntactic information, creating a potential gap between vector representation and logical structure.

This research addresses this gap by investigating the structure of query embedding spaces across both academic benchmarks (384D) and production environments (768D). To establish a robust routing layer, the initial pipeline optimization, hyperparameter tuning, and kernel selection evaluations were conducted on the baseline Spider dataset [1]. Once optimized, the entire pipeline was scaled and migrated to the 768-dimensional production enterprise database environment. Specifically, the problem is formalized by addressing four core questions:
1. **Intrinsic Dimensionality**: How much of the variance in query embeddings is captured by a small number of principal components, and is the effective dimensionality of the space significantly lower than its nominal dimension? [6]
2. **Geometric Clustering**: Do queries of similar syntactic or semantic complexity cluster together cohesively in the embedding space, or are they geometrically dispersed?
3. **Complexity Classification**: Can a supervised classifier, trained on a low-dimensional projection of the embedding space, reliably distinguish discrete query complexity tiers?
4. **Sensitivity and Trade-offs**: What is the sensitivity of classification performance to the number of PCA components retained, and at what point does further dimensionality reduction degrade downstream classification?

By answering these questions, this study establishes a principled mathematical basis for optimizing vector indices, reducing storage footprints, and constructing high-efficiency query routing layers in enterprise Text-to-SQL systems."""

# 3. Conclusion
target_concl = """## 7 Conclusion
This study has presented a principled geometric characterization of query embedding spaces in RAG-based Text-to-SQL systems, demonstrating a joint PCA-SVM framework to optimize database retrieval and model inference. By analyzing both the 384-dimensional academic Spider baseline and a 768-dimensional production environment, the transition from high-dimensional semantic vectors to structurally distinct complexity categories was successfully mapped. The unsupervised manifold analysis revealed that while a compact subspace of 50 PCA components captures the broad thematic core of queries, it discards the subtle logical features encoded in the mathematical "tail" of the variance. Expanding the projection to 179 components (for the baseline) and 220 components (for the production environment) captures 90% of the total variance, successfully preserving the logical markers required to differentiate complex SQL queries.

Furthermore, the experiments validate that query embedding spaces cluster primarily by domain topic rather than syntactic structure, resulting in a highly interlocked spatial layout. This challenge was addressed by deploying a Support Vector Machine (SVM) equipped with a non-linear Radial Basis Function (RBF) kernel, which effectively maps these overlapping boundaries. The optimized SVM-RBF model achieves high classification accuracy across all complexity levels, enabled by customized class-balancing weights. When scaled to the higher-dimensional production manifold, the classifier benefited from superior geometric separability, yielding a 10-point increase in macro F1-score (from 0.71 to 0.81).

In terms of production engineering, the joint framework provides a robust foundation for building cost-efficient, low-latency architectures. Compressing the vector dimensions by over 71% translates directly to a 70.7% reduction in index storage size and accelerates nearest-neighbor search, while the query classification layer provides the technical blueprint for routing simple queries to low-cost LLMs. Future research directions will explore the integration of dynamic, online PCA update algorithms to handle drifting vocabularies without requiring full manifold recalculations, and investigate the extension of this geometric routing framework to multimodal databases and multi-lingual RAG pipelines."""

replace_concl = """## 7 Conclusion
This study has presented a principled geometric characterization of query embedding spaces in RAG-based Text-to-SQL systems, demonstrating a joint PCA-SVM framework to optimize database retrieval and model inference. By analyzing both the 384-dimensional academic Spider baseline and a 768-dimensional production environment, the transition from high-dimensional semantic vectors to structurally distinct complexity categories was successfully mapped. The unsupervised manifold analysis revealed that while a compact subspace of 50 PCA components captures the broad thematic core of queries, it discards the subtle logical features encoded in the mathematical "tail" of the variance. Expanding the projection to 179 components (for the baseline) and 220 components (for the production environment) captures 90% of the total variance, successfully preserving the logical markers required to differentiate complex SQL queries.

Furthermore, the experiments validate that query embedding spaces cluster primarily by domain topic rather than syntactic structure, resulting in a highly interlocked spatial layout. This challenge was addressed by deploying a Support Vector Machine (SVM) equipped with a non-linear Radial Basis Function (RBF) kernel, which effectively maps these overlapping boundaries. The optimized SVM-RBF model achieves high classification accuracy across all complexity levels, enabled by customized class-balancing weights. When scaled to the higher-dimensional production manifold, the classifier benefited from superior geometric separability, yielding a 10-point increase in macro F1-score (from 0.71 to 0.81).

In terms of production engineering, the joint framework provides a robust foundation for building cost-efficient, low-latency architectures. Compressing the vector dimensions by over 71% translates directly to a 70.7% reduction in index storage size and accelerates nearest-neighbor search, while the query classification layer provides the technical blueprint for routing simple queries to low-cost LLMs. The extremely low execution overhead of the SVM-RBF router (under one millisecond) makes it highly suitable for real-time routing cascades.

The theoretical implications of this study highlight a fundamental semantic-structural gap in modern text embeddings. Because contrastive representation models are optimized to group queries by lexical and thematic similarity, they fail to preserve the syntactic differences necessary for SQL difficulty classification. Future embedding architectures should investigate joint training objectives that incorporate structural syntax trees alongside semantic context to capture logical pathways. Additionally, future research directions will explore the integration of dynamic, online PCA update algorithms to handle drifting vocabularies without requiring full manifold recalculations, and investigate the extension of this geometric routing framework to multimodal databases and multi-lingual RAG pipelines."""

replacements = [
    (target_abs, replace_abs),
    (target_intro, replace_intro),
    (target_concl, replace_concl),
]

for idx, (target, replacement) in enumerate(replacements, 1):
    target_clean = target.replace('\r\n', '\n').strip()
    content_clean = content.replace('\r\n', '\n')
    if target_clean in content_clean:
        content = content_clean.replace(target_clean, replacement.strip())
        print(f"Narrative replacement {idx} succeeded.")
    else:
        # Try without stripping
        if target.replace('\r\n', '\n') in content_clean:
            content = content_clean.replace(target.replace('\r\n', '\n'), replacement)
            print(f"Narrative replacement {idx} succeeded (exact match).")
        else:
            print(f"Narrative replacement {idx} FAILED to find match.")

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)
