import re

file_path = r'c:\Users\Dell1234\.gemini\antigravity\scratch\ml_project\paper_revised_draft.md'

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Replacement 1: Difficulty Classifier Logic
target_1 = 'Because the routing decision must be executed on the user query *before* the SQL is generated by the LLM, the system cannot access the SQL structure directly at runtime.'
replace_1 = 'The system cannot access the SQL structure directly at runtime, as the routing decision must be executed on the user query *before* the SQL is generated by the LLM.'

# Replacement 2: PCA Tail
target_2 = 'Because complex SQL logical tokens (such as specific clauses, nesting, or set operators) are encoded in the "tail" of the embedding variance rather than the global semantic directions, this aggressive compression discarded vital structural cues.'
replace_2 = 'This aggressive compression discarded vital structural cues, as complex SQL logical tokens (such as specific clauses, nesting, or set operators) are encoded in the "tail" of the embedding variance rather than the global semantic directions.'

# Replacement 3: Conclusion
target_3 = 'Because contrastive representation models are optimized to group queries by lexical and thematic similarity, they fail to preserve the syntactic differences necessary for SQL difficulty classification.'
replace_3 = 'Contrastive representation models fail to preserve the syntactic differences necessary for SQL difficulty classification, as they are optimized to group queries by lexical and thematic similarity.'

replacements = [
    (target_1, replace_1),
    (target_2, replace_2),
    (target_3, replace_3),
]

for idx, (target, replacement) in enumerate(replacements, 1):
    target_clean = target.replace('\r\n', '\n').strip()
    content_clean = content.replace('\r\n', '\n')
    if target_clean in content_clean:
        content = content_clean.replace(target_clean, replacement.strip())
        print(f"Because replacement {idx} succeeded.")
    else:
        # Try without stripping
        if target.replace('\r\n', '\n') in content_clean:
            content = content_clean.replace(target.replace('\r\n', '\n'), replacement)
            print(f"Because replacement {idx} succeeded (exact match).")
        else:
            print(f"Because replacement {idx} FAILED to find match.")

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(content)
